// このファイルは自動生成されます
// 編集する場合は video-settings.yaml を編集してください
// npm run sync-settings で再生成されます

export const SETTINGS = {
  "font": {
    "family": "M PLUS Rounded 1c",
    "size": 70,
    "weight": "900",
    "color": "#ffffff",
    "outlineColor": "character",
    "innerOutlineColor": "none"
  },
  "subtitle": {
    "bottomOffset": 40,
    "maxWidthPercent": 55,
    "maxWidthPixels": 1000,
    "outlineWidth": 14,
    "innerOutlineWidth": 8
  },
  "character": {
    "height": 275,
    "useImages": true,
    "imagesBasePath": "images"
  },
  "content": {
    "topPadding": 0,
    "sidePadding": 0,
    "bottomPadding": 0
  },
  "video": {
    "width": 1920,
    "height": 1080,
    "fps": 30,
    "playbackRate": 1.2
  },
  "colors": {
    "background": "#ffffff",
    "text": "#ffffff",
    "zundamon": "#228B22",
    "metan": "#FF1493"
  }
} as const;

// キャラクターごとの利用可能な画像ファイル
export const AVAILABLE_IMAGES: Record<string, string[]> = {
  "metan": [
    "angry_close.png",
    "angry_open.png",
    "happy_close.png",
    "happy_open.png",
    "holding/angry_close.png",
    "holding/angry_open.png",
    "holding/happy_close.png",
    "holding/happy_open.png",
    "holding/mouth_close.png",
    "holding/mouth_open.png",
    "holding/sad_close.png",
    "holding/sad_open.png",
    "holding/surprised_close.png",
    "holding/surprised_open.png",
    "holding/thinking_close.png",
    "holding/thinking_open.png",
    "mouth_close.png",
    "mouth_open.png",
    "normal/angry_close.png",
    "normal/angry_open.png",
    "normal/happy_close.png",
    "normal/happy_open.png",
    "normal/mouth_close.png",
    "normal/mouth_open.png",
    "normal/sad_close.png",
    "normal/sad_open.png",
    "normal/surprised_close.png",
    "normal/surprised_open.png",
    "normal/thinking_close.png",
    "normal/thinking_open.png",
    "pointing/angry_close.png",
    "pointing/angry_open.png",
    "pointing/happy_close.png",
    "pointing/happy_open.png",
    "pointing/mouth_close.png",
    "pointing/mouth_open.png",
    "pointing/sad_close.png",
    "pointing/sad_open.png",
    "pointing/surprised_close.png",
    "pointing/surprised_open.png",
    "pointing/thinking_close.png",
    "pointing/thinking_open.png",
    "sad_close.png",
    "sad_open.png",
    "surprised_close.png",
    "surprised_open.png",
    "thinking/angry_close.png",
    "thinking/angry_open.png",
    "thinking/happy_close.png",
    "thinking/happy_open.png",
    "thinking/mouth_close.png",
    "thinking/mouth_open.png",
    "thinking/sad_close.png",
    "thinking/sad_open.png",
    "thinking/surprised_close.png",
    "thinking/surprised_open.png",
    "thinking/thinking_close.png",
    "thinking/thinking_open.png",
    "thinking_close.png",
    "thinking_open.png"
  ],
  "tsumugi": [
    "angry_close.png",
    "angry_open.png",
    "happy_close.png",
    "happy_open.png",
    "mouth_close.png",
    "mouth_open.png",
    "normal/angry_close.png",
    "normal/angry_open.png",
    "normal/happy_close.png",
    "normal/happy_open.png",
    "normal/mouth_close.png",
    "normal/mouth_open.png",
    "normal/sad_close.png",
    "normal/sad_open.png",
    "normal/surprised_close.png",
    "normal/surprised_open.png",
    "normal/thinking_close.png",
    "normal/thinking_open.png",
    "normal_close.png",
    "normal_open.png",
    "peace/angry_close.png",
    "peace/angry_open.png",
    "peace/happy_close.png",
    "peace/happy_open.png",
    "peace/mouth_close.png",
    "peace/mouth_open.png",
    "peace/sad_close.png",
    "peace/sad_open.png",
    "peace/surprised_close.png",
    "peace/surprised_open.png",
    "peace/thinking_close.png",
    "peace/thinking_open.png",
    "pointing/angry_close.png",
    "pointing/angry_open.png",
    "pointing/happy_close.png",
    "pointing/happy_open.png",
    "pointing/mouth_close.png",
    "pointing/mouth_open.png",
    "pointing/sad_close.png",
    "pointing/sad_open.png",
    "pointing/surprised_close.png",
    "pointing/surprised_open.png",
    "pointing/thinking_close.png",
    "pointing/thinking_open.png",
    "sad_close.png",
    "sad_open.png",
    "surprised_close.png",
    "surprised_open.png",
    "thinking_close.png",
    "thinking_open.png"
  ],
  "zundamon": [
    "angry_close.png",
    "angry_open.png",
    "confident/angry_close.png",
    "confident/angry_open.png",
    "confident/happy_close.png",
    "confident/happy_open.png",
    "confident/mouth_close.png",
    "confident/mouth_open.png",
    "confident/sad_close.png",
    "confident/sad_open.png",
    "confident/surprised_close.png",
    "confident/surprised_open.png",
    "confident/thinking_close.png",
    "confident/thinking_open.png",
    "hands_up/angry_close.png",
    "hands_up/angry_open.png",
    "hands_up/happy_close.png",
    "hands_up/happy_open.png",
    "hands_up/mouth_close.png",
    "hands_up/mouth_open.png",
    "hands_up/sad_close.png",
    "hands_up/sad_open.png",
    "hands_up/surprised_close.png",
    "hands_up/surprised_open.png",
    "hands_up/thinking_close.png",
    "hands_up/thinking_open.png",
    "happy_close.png",
    "happy_open.png",
    "mouth_close.png",
    "mouth_open.png",
    "normal/angry_close.png",
    "normal/angry_open.png",
    "normal/happy_close.png",
    "normal/happy_open.png",
    "normal/mouth_close.png",
    "normal/mouth_open.png",
    "normal/sad_close.png",
    "normal/sad_open.png",
    "normal/surprised_close.png",
    "normal/surprised_open.png",
    "normal/thinking_close.png",
    "normal/thinking_open.png",
    "pointing/angry_close.png",
    "pointing/angry_open.png",
    "pointing/happy_close.png",
    "pointing/happy_open.png",
    "pointing/mouth_close.png",
    "pointing/mouth_open.png",
    "pointing/sad_close.png",
    "pointing/sad_open.png",
    "pointing/surprised_close.png",
    "pointing/surprised_open.png",
    "pointing/thinking_close.png",
    "pointing/thinking_open.png",
    "sad_close.png",
    "sad_open.png",
    "surprised_close.png",
    "surprised_open.png",
    "thinking_close.png",
    "thinking_open.png"
  ]
};

export type VideoSettings = typeof SETTINGS;
